# Generated by Django 3.0.3 on 2020-02-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='raison_sociale',
            new_name='raison_social',
        ),
        migrations.AlterField(
            model_name='client',
            name='tel',
            field=models.CharField(max_length=30),
        ),
    ]
