# Generated by Django 3.0.3 on 2020-02-17 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0002_auto_20200217_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignedevis',
            name='total',
        ),
    ]
